
export const elementsData/*: ElementsData[]*/ = [
    {
        atomicNumber: 1,
        group: 1,
        period: 0,
        atomicMass: 1.00794,
        name: "hydrogen",
        symbol: "h",
        special: false,
        state: "gas",
        electronConfiguration: "",
        metalMetalloidNonmetal: "reactive nonmetal",
        /*electronicConfiguration: "1s1",
        boilingCelsiusTemperature: -252.87,
        fusionCelsiusTemperature: -259.34,
        relativeDensity: "0.08988*(p. triple)",
        commonOxidationStates: 1,
        calorVaporizacion: 0.904,
        calorFusion: 0.117,
        calorEspecifico: 5.40,
        state: ElementStates.GAS,
        conductividadTermica: 0.001815,
        atomicVolume: undefined,
        firstIonizedPotencial: 13.598,
        solubleEn: "H2O",
        propiedadesAcidoBasicas: { type: AcidBasicProperty.ACID_BASIC },
        sistemaCristalino: "hexagonal",
        color: "incoloro",
        radioIonico: "125-155(H-)",
        radioCovalente: 30,
        electroNegativity: 2.1*/
    },
    {
        atomicNumber: 2,
        group: 0,
        period: 0,
        atomicMass: 4.002602,
        name: "helium",
        symbol: "he",
        special: false,
        state: "gas",
        electronConfiguration: "",
        metalMetalloidNonmetal: "noble gas",
        /*electronicConfiguration: "1s2",
        boilingCelsiusTemperature: -268.934,
        fusionCelsiusTemperature: "-272.2(26atm)",
        relativeDensity: "0.17847*(T Boyle)",
        calorVaporizacion: 0.0832,
        calorFusion: "0.050(-273º)",
        calorEspecifico: 5.196,
        state: ElementStates.GAS,
        conductividadTermica: 0.001520,
        firstIonizedPotencial: 24.587,
        solubleEn: "H2O",
        propiedadesAcidoBasicas: { type: AcidBasicProperty.NEUTRAL },
        sistemaCristalino: "hexagonal",
        color: "incoloro"*/
    },
    {
        atomicNumber: 3,
        group: 1,
        period: 0,
        atomicMass: 6.941,
        name: "lithium",
        symbol: "li",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkali metal",
        /*electronicConfiguration: "1s2 2s1",
        boilingCelsiusTemperature: 1342,
        fusionCelsiusTemperature: 180.54,
        relativeDensity: 0.534,
        commonOxidationStates: 1,
        calorVaporizacion: 134.7,
        calorFusion: 2.99,
        calorEspecifico: 3.39,
        state: ElementStates.SOLID,
        resistividadElectrica: 8.55,
        conductividadTermica: 0.848,
        atomicVolume: 13.0,
        firstIonizedPotencial: 5.392,
        solubleEn: "H2O desc",
        propiedadesAcidoBasicas: { type: AcidBasicProperty.BASIC, intensity: 1 },
        sistemaCristalino: "bodyCenteredCubic",
        color: "plateado",
        radioIonico: 68,
        atomicRadio: 173,
        radioCovalente: 122.5,
        electroNegativity: 1.0,*/
    },
    {
        atomicNumber: 4,
        group: 2,
        period: 0,
        atomicMass: 9.012182,
        name: "beryllium",
        symbol: "be",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkaline earth metal",
    },
    {
        atomicNumber: 5,
        group: 0,
        period: 0,
        atomicMass: 10.811,
        name: "boron",
        symbol: "b",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "metalloid",
    },
    {
        atomicNumber: 6,
        group: 0,
        period: 0,
        atomicMass: 12.011,
        name: "carbon",
        symbol: "c",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "reactive nonmetal",
    },
    {
        atomicNumber: 7,
        group: 0,
        period: 0,
        atomicMass: 14.00674,
        name: "nitrogen",
        symbol: "n",
        special: false,
        state: "gas",
        electronConfiguration: "",
        metalMetalloidNonmetal: "reactive nonmetal",
    },
    {
        atomicNumber: 8,
        group: 0,
        period: 0,
        atomicMass: 15.9994,
        name: "oxygen",
        symbol: "o",
        special: false,
        state: "gas",
        electronConfiguration: "",
        metalMetalloidNonmetal: "reactive nonmetal",
    },
    {
        atomicNumber: 9,
        group: 0,
        period: 0,
        atomicMass: 18.9984032,
        name: "fluorine",
        symbol: "f",
        special: false,
        state: "gas",
        electronConfiguration: "",
        metalMetalloidNonmetal: "reactive nonmetal",
    },
    {
        atomicNumber: 10,
        group: 0,
        period: 0,
        atomicMass: 20.1797,
        name: "neon",
        symbol: "ne",
        special: false,
        state: "gas",
        electronConfiguration: "",
        metalMetalloidNonmetal: "noble gas",
    },
    {
        atomicNumber: 11,
        group: 1,
        period: 0,
        atomicMass: 22.989768,
        name: "sodium",
        symbol: "na",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkali metal",
    },
    {
        atomicNumber: 12,
        group: 2,
        period: 0,
        atomicMass: 24.3050,
        name: "magnesium",
        symbol: "mg",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkaline earth metal",
    },
    {
        atomicNumber: 13,
        group: 0,
        period: 0,
        atomicMass: 26.981539,
        name: "aluminum",
        symbol: "al",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "post-​transition metal",
    },
    {
        atomicNumber: 14,
        group: 0,
        period: 0,
        atomicMass: 28.0855,
        name: "silicon",
        symbol: "si",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "metalloid",
    },
    {
        atomicNumber: 15,
        group: 0,
        period: 0,
        atomicMass: 30.973762,
        name: "phosphorus",
        symbol: "p",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "reactive nonmetal",
    },
    {
        atomicNumber: 16,
        group: 0,
        period: 0,
        atomicMass: 32.066,
        name: "sulfur",
        symbol: "s",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "reactive nonmetal",
    },
    {
        atomicNumber: 17,
        group: 0,
        period: 0,
        atomicMass: 35.4527,
        name: "chlorine",
        symbol: "cl",
        special: false,
        state: "gas",
        electronConfiguration: "",
        metalMetalloidNonmetal: "reactive nonmetal",
    },
    {
        atomicNumber: 18,
        group: 0,
        period: 0,
        atomicMass: 39.948,
        name: "argon",
        symbol: "ar",
        special: false,
        state: "gas",
        electronConfiguration: "",
        metalMetalloidNonmetal: "noble gas",
    },
    {
        atomicNumber: 19,
        group: 1,
        period: 0,
        atomicMass: 39.0983,
        name: "potassium",
        symbol: "k",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkali metal",
    },
    {
        atomicNumber: 20,
        group: 2,
        period: 0,
        atomicMass: 4.078,
        name: "calcium",
        symbol: "ca",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkaline earth metal",
    },
    {
        atomicNumber: 21,
        group: 3,
        period: 0,
        atomicMass: 44.9559,
        name: "scandium",
        symbol: "sc",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 22,
        group: 0,
        period: 0,
        atomicMass: 47.88,
        name: "titanium",
        symbol: "ti",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 23,
        group: 5,
        period: 0,
        atomicMass: 50.9415,
        name: "vanadium",
        symbol: "v",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 24,
        group: 6,
        period: 0,
        atomicMass: 51.9961,
        name: "chromium",
        symbol: "cr",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 25,
        group: 7,
        period: 0,
        atomicMass: 54.93805,
        name: "manganese",
        symbol: "mn",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 26,
        group: 0,
        period: 0,
        atomicMass: 55.847,
        name: "iron",
        symbol: "fe",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 27,
        group: 9,
        period: 0,
        atomicMass: 58.93320,
        name: "cobalt",
        symbol: "co",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 28,
        group: 0,
        period: 0,
        atomicMass: 58.69,
        name: "nickel",
        symbol: "ni",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 29,
        group: 0,
        period: 0,
        atomicMass: 63.546,
        name: "copper",
        symbol: "cu",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 30,
        group: 0,
        period: 0,
        atomicMass: 65.39,
        name: "zinc",
        symbol: "zn",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "post-​transition metal",
    },
    {
        atomicNumber: 31,
        group: 0,
        period: 0,
        atomicMass: 69.723,
        name: "gallium",
        symbol: "ga",
        special: false,
        state: "liquid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "post-​transition metal",
    },
    {
        atomicNumber: 32,
        group: 0,
        period: 0,
        atomicMass: 72.61,
        name: "germanium",
        symbol: "ge",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "metalloid",
    },
    {
        atomicNumber: 33,
        group: 0,
        period: 0,
        atomicMass: 74.92159,
        name: "arsenic",
        symbol: "as",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "metalloid",
    },
    {
        atomicNumber: 34,
        group: 0,
        period: 0,
        atomicMass: 78.96,
        name: "selenium",
        symbol: "se",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "reactive nonmetal",
    },
    {
        atomicNumber: 35,
        group: 0,
        period: 0,
        atomicMass: 79.904,
        name: "bromine",
        symbol: "br",
        special: false,
        state: "liquid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "reactive nonmetal",
    },
    {
        atomicNumber: 36,
        group: 0,
        period: 0,
        atomicMass: 83.80,
        name: "krypton",
        symbol: "kr",
        special: false,
        state: "gas",
        electronConfiguration: "",
        metalMetalloidNonmetal: "noble gas",
    },
    {
        atomicNumber: 37,
        group: 1,
        period: 0,
        atomicMass: 85.4578,
        name: "rubidium",
        symbol: "rb",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkali metal",
    },
    {
        atomicNumber: 38,
        group: 2,
        period: 0,
        atomicMass: 87.62,
        name: "strontium",
        symbol: "sr",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkaline earth metal",
    },
    {
        atomicNumber: 39,
        group: 3,
        period: 0,
        atomicMass: 88.90585,
        name: "yttrium",
        symbol: "y",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 40,
        group: 4,
        period: 0,
        atomicMass: 91.224,
        name: "zirconium",
        symbol: "zr",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 41,
        group: 5,
        period: 0,
        atomicMass: 92.90638,
        name: "niobium",
        symbol: "nb",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 42,
        group: 6,
        period: 0,
        atomicMass: 95.94,
        name: "molybdenum",
        symbol: "mo",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 43,
        group: 7,
        period: 0,
        atomicMass: 98,
        name: "technetium",
        symbol: "tc",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 44,
        group: 8,
        period: 0,
        atomicMass: 101.07,
        name: "ruthenium",
        symbol: "ru",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 45,
        group: 9,
        period: 0,
        atomicMass: 102.90550,
        name: "rhodium",
        symbol: "rh",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 46,
        group: 0,
        period: 0,
        atomicMass: 106.42,
        name: "palladium",
        symbol: "pd",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 47,
        group: 0,
        period: 0,
        atomicMass: 107.8682,
        name: "silver",
        symbol: "ag",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 48,
        group: 0,
        period: 0,
        atomicMass: 112.411,
        name: "cadmium",
        symbol: "cd",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "post-​transition metal",
    },
    {
        atomicNumber: 49,
        group: 0,
        period: 0,
        atomicMass: 114.82,
        name: "indium",
        symbol: "in",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "post-​transition metal",
    },
    {
        atomicNumber: 50,
        group: 0,
        period: 0,
        atomicMass: 118.710,
        name: "tin",
        symbol: "sn",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "post-​transition metal",
    },
    {
        atomicNumber: 51,
        group: 0,
        period: 0,
        atomicMass: 121.75,
        name: "antimony",
        symbol: "sb",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "metalloid",
    },
    {
        atomicNumber: 52,
        group: 0,
        period: 0,
        atomicMass: 127.60,
        name: "tellurium",
        symbol: "te",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "metalloid",
    },
    {
        atomicNumber: 53,
        group: 0,
        period: 0,
        atomicMass: 126.90447,
        name: "iodine",
        symbol: "i",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "reactive nonmetal",
    },
    {
        atomicNumber: 54,
        group: 0,
        period: 0,
        atomicMass: 131.29,
        name: "xenon",
        symbol: "xe",
        special: false,
        state: "gas",
        electronConfiguration: "",
        metalMetalloidNonmetal: "noble gas",
    },
    {
        atomicNumber: 55,
        group: 1,
        period: 0,
        atomicMass: 132.90543,
        name: "cesium",
        symbol: "cs",
        special: false,
        state: "liquid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkali metal",
    },
    {
        atomicNumber: 56,
        group: 2,
        period: 0,
        atomicMass: 137.327,
        name: "barium",
        symbol: "ba",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkaline earth metal",
    },
    {
        atomicNumber: 57,
        group: 0,
        period: 0,
        atomicMass: 138.9055,
        name: "lanthanum",
        symbol: "la",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 72,
        group: 4,
        period: 0,
        atomicMass: 178.49,
        name: "hafnium",
        symbol: "hf",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 73,
        group: 5,
        period: 0,
        atomicMass: 180.9479,
        name: "tantalum",
        symbol: "ta",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 74,
        group: 6,
        period: 0,
        atomicMass: 183.85,
        name: "tungsten",
        symbol: "w",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 75,
        group: 7,
        period: 0,
        atomicMass: 186.207,
        name: "rhenium",
        symbol: "re",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 76,
        group: 8,
        period: 0,
        atomicMass: 190.2,
        name: "osmium",
        symbol: "os",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 77,
        group: 9,
        period: 0,
        atomicMass: 192.22,
        name: "iridium",
        symbol: "ir",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 78,
        group: 0,
        period: 0,
        atomicMass: 195.08,
        name: "platinum",
        symbol: "pt",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 79,
        group: 0,
        period: 0,
        atomicMass: 196.96654,
        name: "gold",
        symbol: "au",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 80,
        group: 0,
        period: 0,
        atomicMass: 200.59,
        name: "mercury",
        symbol: "hg",
        special: false,
        state: "liquid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "post-​transition metal",
    },
    {
        atomicNumber: 81,
        group: 4,
        period: 0,
        atomicMass: 204.3833,
        name: "thallium",
        symbol: "ti",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "post-​transition metal",
    },
    {
        atomicNumber: 82,
        group: 0,
        period: 0,
        atomicMass: 207.2,
        name: "lead",
        symbol: "pb",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "post-​transition metal",
    },
    {
        atomicNumber: 83,
        group: 0,
        period: 0,
        atomicMass: 208.98037,
        name: "bismuth",
        symbol: "bi",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "post-​transition metal",
    },
    {
        atomicNumber: 84,
        group: 0,
        period: 0,
        atomicMass: 209,
        name: "polonium",
        symbol: "po",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "post-​transition metal",
    },
    {
        atomicNumber: 85,
        group: 0,
        period: 0,
        atomicMass: 210,
        name: "astatine",
        symbol: "at",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "metalloid",
    },
    {
        atomicNumber: 86,
        group: 0,
        period: 0,
        atomicMass: 222,
        name: "radon",
        symbol: "rn",
        special: false,
        state: "gas",
        electronConfiguration: "",
        metalMetalloidNonmetal: "noble gas",
    },
    {
        atomicNumber: 87,
        group: 1,
        period: 0,
        atomicMass: 223,
        name: "francium",
        symbol: "fr",
        special: false,
        state: "liquid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkali metal",
    },
    {
        atomicNumber: 88,
        group: 2,
        period: 0,
        atomicMass: 226.025,
        name: "radium",
        symbol: "ra",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "alkaline earth metal",
    },
    {
        atomicNumber: 89,
        group: 0,
        period: 0,
        atomicMass: 227.028,
        name: "actinium",
        symbol: "ac",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 104,
        group: 4,
        period: 0,
        atomicMass: 261,
        name: "rutherfordium",
        symbol: "rf",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 105,
        group: 5,
        period: 0,
        atomicMass: 262,
        name: "dubnium",
        symbol: "db",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 106,
        group: 6,
        period: 0,
        atomicMass: 263,
        name: "seaborgium",
        symbol: "sg",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 107,
        group: 7,
        period: 0,
        atomicMass: 264,
        name: "bohrium",
        symbol: "bh",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 108,
        group: 8,
        period: 0,
        atomicMass: 265,
        name: "hassium",
        symbol: "hs",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "transition metal",
    },
    {
        atomicNumber: 109,
        group: 9,
        period: 0,
        atomicMass: 266,
        name: "meitnerium",
        symbol: "mt",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "unknown",
    },
    {
        atomicNumber: 110,
        group: 0,
        period: 0,
        atomicMass: 269,
        name: "darmstadtium",
        symbol: "ds",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "unknown",
    },
    {
        atomicNumber: 111,
        group: 0,
        period: 0,
        atomicMass: 272,
        name: "roentgenium",
        symbol: "rg",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "unknown",
    },
    {
        atomicNumber: 112,
        group: 0,
        period: 0,
        atomicMass: 277,
        name: "ununbio",
        symbol: "uub",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "",
    },
    {
        atomicNumber: 113,
        group: 0,
        period: 0,
        atomicMass: 277,
        name: "ununtrio",
        symbol: "uut",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "",
    },
    {
        atomicNumber: 114,
        group: 0,
        period: 0,
        atomicMass: 285,
        name: "ununquadio",
        symbol: "uuq",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "",
    },
    {
        atomicNumber: 115,
        group: 0,
        period: 0,
        atomicMass: 0,
        name: "ununpentio",
        symbol: "uup",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "",
    },
    {
        atomicNumber: 116,
        group: 0,
        period: 0,
        atomicMass: 289,
        name: "ununhexio",
        symbol: "uuh",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "",
    },
    {
        atomicNumber: 117,
        group: 0,
        period: 0,
        atomicMass: 0,
        name: "ununseptio",
        symbol: "uus",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "",
    },
    {
        atomicNumber: 118,
        group: 0,
        period: 0,
        atomicMass: 293,
        name: "ununqoctio",
        symbol: "uuo",
        special: true,
        state: "gas ?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "",
    },
    {
        atomicNumber: 119,
        group: 1,
        period: 0,
        atomicMass: 0,
        name: "ununenio",
        symbol: "uue",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "",
    },
    {
        atomicNumber: 120,
        group: 2,
        period: 0,
        atomicMass: 0,
        name: "unbinilio",
        symbol: "ubn",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "",
    },
    {
        atomicNumber: 121,
        group: 0,
        period: 0,
        atomicMass: 0,
        name: "unbiunio",
        symbol: "ubu",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "",
    },
    {
        atomicNumber: 58,
        group: 0,
        period: 0,
        atomicMass: 140.115,
        name: "cerium",
        symbol: "ce",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 59,
        group: 0,
        period: 0,
        atomicMass: 140.90765,
        name: "praseodymium",
        symbol: "pr",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 60,
        group: 0,
        period: 0,
        atomicMass: 144.24,
        name: "neodymium",
        symbol: "nd",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 61,
        group: 0,
        period: 0,
        atomicMass: 145,
        name: "promethium",
        symbol: "pm",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 62,
        group: 0,
        period: 0,
        atomicMass: 150.36,
        name: "samarium",
        symbol: "sm",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 63,
        group: 0,
        period: 0,
        atomicMass: 151.965,
        name: "europium",
        symbol: "eu",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 64,
        group: 0,
        period: 0,
        atomicMass: 157.25,
        name: "gadolinium",
        symbol: "gd",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 65,
        group: 0,
        period: 0,
        atomicMass: 158.92534,
        name: "terbium",
        symbol: "tb",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 66,
        group: 0,
        period: 0,
        atomicMass: 162.50,
        name: "dysprosium",
        symbol: "dy",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 67,
        group: 0,
        period: 0,
        atomicMass: 164.93032,
        name: "holmium",
        symbol: "ho",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 68,
        group: 0,
        period: 0,
        atomicMass: 167.26,
        name: "erbium",
        symbol: "er",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 69,
        group: 0,
        period: 0,
        atomicMass: 168.9342,
        name: "thulium",
        symbol: "tm",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 70,
        group: 0,
        period: 0,
        atomicMass: 173.04,
        name: "ytterbium",
        symbol: "yb",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },

    {
        atomicNumber: 71,
        group: 0,
        period: 0,
        atomicMass: 174.967,
        name: "lutetium",
        symbol: "lu",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "lan­thanide",
    },
    {
        atomicNumber: 90,
        group: 0,
        period: 0,
        atomicMass: 232.0381,
        name: "thorium",
        symbol: "th",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 91,
        group: 0,
        period: 0,
        atomicMass: 231.0359,
        name: "protactinium",
        symbol: "pa",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 92,
        group: 0,
        period: 0,
        atomicMass: 238.0289,
        name: "uranium",
        symbol: "u",
        special: false,
        state: "solid",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 93,
        group: 0,
        period: 0,
        atomicMass: 237.048,
        name: "neptunium",
        symbol: "np",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 94,
        group: 0,
        period: 0,
        atomicMass: 244,
        name: "plutonium",
        symbol: "pu",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 95,
        group: 0,
        period: 0,
        atomicMass: 243,
        name: "americium",
        symbol: "am",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 96,
        group: 0,
        period: 0,
        atomicMass: 247,
        name: "curium",
        symbol: "cm",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 97,
        group: 0,
        period: 0,
        atomicMass: 247,
        name: "berkelium",
        symbol: "bk",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 98,
        group: 0,
        period: 0,
        atomicMass: 251,
        name: "californium",
        symbol: "cf",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 99,
        group: 0,
        period: 0,
        atomicMass: 252,
        name: "einsteinium",
        symbol: "es",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 100,
        group: 8,
        period: 0,
        atomicMass: 257,
        name: "fermium",
        symbol: "fm",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 101,
        group: 0,
        period: 0,
        atomicMass: 258,
        name: "mendelevium",
        symbol: "md",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 102,
        group: 0,
        period: 0,
        atomicMass: 259,
        name: "nobelium",
        symbol: "no",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
    {
        atomicNumber: 103,
        group: 0,
        period: 0,
        atomicMass: 260,
        name: "lawrencium",
        symbol: "lr",
        special: true,
        state: "?",
        electronConfiguration: "",
        metalMetalloidNonmetal: "actinide",
    },
];