export enum ElementCategories {
	ACTINIDE = "ACTINIDE",
	ALKALI_METAL = "ALKALI_METAL",
	ALKALINE_EARTH_METAL = "ALKALINE_EARTH_METAL",
	LANTHANIDE = "LANTHANIDE",
	METALLOID = "METALLOID",
	NOBLE_GAS = "NOBLE_GAS",
	POST_TRANSITION_METAL = "POST_TRANSITION_METAL",
	REACTIVE_NONMETAL = "REACTIVE_NONMETAL",
	TRANSITION_METAL = "TRANSITION_METAL",
	UNKNOWN = "UNKNOWN"
}

export default ElementCategories;